### ISSUE TITLE
Comparison against ClassMate

### ISSUE THREAD

**Issue by JoshRosen** [jhalterman/typetools#21] opened 2016-03-29 21:32 UTC
It looks like the TypeTools and [ClassMate](https://github.com/FasterXML/java-classmate) libraries have similar goals. Do you have a short summary of the key differences / strengths of each library?

**Comment by jhalterman** [comment] 2016-03-30 00:15
I can't speak to @cowtowncoder's motivation for ClassMate, but TypeTools was intended to be a dead simple API built into a lightweight, zero-dependency library for resolving generic type information that covers the most common the use cases one would have for such a library which is raw type argument resolution, including from lambdas and method references.

The important way that TypeTools and ClassMate currently differ is that ClassMate allows you to resolve parameterized type information that can be further introspected. An example of where this comes up:

```
interface Foo<T> {}
class Bar implements Foo<List<Integer>> {}

Class<?> typeArg = TypeResolver.resolveRawArgument(Foo.class, Bar.class);

assert typeArg == List.class;
```

Here we can resolve `T` to `List`, but that `T` is actually `List<Integer>` is something TypeTools doesn't dig into since this would be returning a `ParameterizedType` rather than a raw Class. ClassMate does allow you to dig into this sort of thing by returning a [ResolvedType](http://fasterxml.github.io/java-classmate/javadoc/1.3/com/fasterxml/classmate/ResolvedType.html) instance.

So generally, if you're just resolving raw type arguments, than consider TypeTools. If you need to introspect deeply into generic type signatures (ie: `<T extends List<Class<? extends Foo>>>`), consider ClassMate. If you need to resolve type arguments from lambdas or method references (I'm not sure if ClassMate supports this?), consider TypeTools with the caveat that this functionality makes use of `sun.reflect.ConstantPool` and will therefore only work on JREs that provide support for this (Sun/Oracle).

**Comment by cowtowncoder** [comment] 2016-03-30 00:48
Sounds like a reasonable summary to me. ClassMate grew out of needs of Jackson databinding, and this is where more nested generic type variable resolution is beneficial.
I can not speak for handling of lambda types or method references wrt classmate: only Java 6 is required so there is no specific handling, although no explicit has been requested. So it might work for some uses.

**Closed** 2016-04-12 03:45 UTC
Labels: Question
