### ISSUE TITLE
TypeResolver.resolveRawArguments is not working with lambdas on JDK 14

### ISSUE THREAD

**Issue by dreis2211** [jhalterman/typetools#70] opened 2021-02-10 19:24 UTC
Hi,

I just found out that the static init block in `TypeResolver` is choking up on `AccessibleObject.class.getDeclaredField("override")` in newer JDKs (I think it's actually broken since JDK12, but I don't have it locally).

Ultimately, this leads to `RESOLVES_LAMBDAS` not being set and therefore to problems when resolving lambdas in `resolveRawArguments`. Unfortunately, the static init block is in a try catch where the exception is silently dropped, so this problem isn't really obvious.

Cheers,
Christoph

**Comment by codetwice** [comment] 2021-03-06 19:17
Is this the reason why arguments are resolved to net.jodah.typetools.TypeResolver.Unknown?

**Comment by chhsiao90** [comment] 2021-04-06 08:59
It should be caused by https://github.com/openjdk/jdk/commit/9c70e26c146ae4c5a2e2311948efec9bf662bb8c

**Comment by chhsiao90** [comment] 2021-04-07 03:55
After investigation, using `VarHandle` works fine but it requires minimum JDK 9 (Reflection over VarHandle doesn't work, see [Calling set on VarHandle in java 14 causes UnsatisfiedLinkError](https://stackoverflow.com/questions/64023617/calling-set-on-varhandle-in-java-14-causes-unsatisfiedlinkerror).

**Comment by chhsiao90** [comment] 2021-04-07 05:15
Just saw there is a pull request fixed this issue #66

**Comment by jhalterman** [comment] 2021-04-09 18:45
Closed by #66.

**Closed by jhalterman** 2021-04-09 18:45 UTC
